# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: adsb.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nadsb.proto\x12\x04\x61\x64sb\"\xde\x02\n\x0e\x41ircraftRecord\x12\x14\n\x0cicao_address\x18\x01 \x01(\r\x12\x10\n\x08\x63\x61llsign\x18\x02 \x01(\t\x12\x10\n\x08latitude\x18\x03 \x01(\x01\x12\x11\n\tlongitude\x18\x04 \x01(\x01\x12\x13\n\x0b\x61ltitude_ft\x18\x05 \x01(\x05\x12\x14\n\x0cground_speed\x18\x06 \x01(\x02\x12\x0f\n\x07heading\x18\x07 \x01(\x02\x12\x15\n\rvertical_rate\x18\x08 \x01(\x02\x12\x14\n\x0ctimestamp_ms\x18\t \x01(\x03\x12\x14\n\x0csignal_power\x18\n \x01(\x02\x12\x11\n\tcrc_valid\x18\x0b \x01(\x08\x12\x17\n\x0f\x64ownlink_format\x18\x0c \x01(\r\x12\x11\n\ttype_code\x18\r \x01(\r\x12\x14\n\x0cis_odd_frame\x18\x0e \x01(\x08\x12\x14\n\x0craw_latitude\x18\x0f \x01(\r\x12\x15\n\rraw_longitude\x18\x10 \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'adsb_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _AIRCRAFTRECORD._serialized_start=21
  _AIRCRAFTRECORD._serialized_end=371
# @@protoc_insertion_point(module_scope)
